## 지금 ec2에 직접 넣어줘야함, 자동화 안되어있음
version: "3"
services:
  app:
    image: ${DOCKER_IMAGE}:latest
    ports:
      - "80:3000"
    restart: always
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    volumes:
      - ./env_file:/var/app/.env
  redis:
    image: redis:latest
    mem_limit: 500M
    ports:
      - "6379:6379"
    restart: always
