version: "3"
services:
  app:
    image: ${{ env.DOCKER_IMAGE }}:latest
    ports:
      - "80:3000"
    restart: always
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    mem_limit: 500M
    ports:
      - "6379:6379"
    restart: always